[cerebrium.deployment]
name = "matrix-inference-node"
python_version = "3.11"
include = [
    "main.py"
]

[cerebrium.hardware]
compute = "ADA_L40"
cpu = 4
memory = 16

[cerebrium.dependencies]
apt = [
    "curl",
    "libgomp1",
    "ca-certificates",
    "tar"
]
pip = []
